"""add_strategy_config_to_researchers

Revision ID: 3748d0d66873
Revises: 50cbe2e78c20
Create Date: 2026-04-19 23:32:25.329373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3748d0d66873'
down_revision: Union[str, None] = '50cbe2e78c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researchers', sa.Column('strategy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researchers', 'strategy_config')
    # ### end Alembic commands ###
