"""add_is_system_to_researchers

Revision ID: b5e3b7731a16
Revises: 3748d0d66873
Create Date: 2026-04-20 00:05:20.279473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e3b7731a16'
down_revision: Union[str, None] = '3748d0d66873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researchers', sa.Column('is_system', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researchers', 'is_system')
    # ### end Alembic commands ###
