from __future__ import annotations

from uuid import uuid4

from fastapi.testclient import TestClient

from app.main import create_app


def _assert_success_payload(response, expected_statuses: tuple[int, ...] = (200,)) -> dict:
    assert response.status_code in expected_statuses
    payload = response.json()
    assert payload["success"] is True
    assert "data" in payload
    return payload


def _assert_list_response_container(data: dict) -> None:
    assert isinstance(data, dict)
    assert isinstance(data.get("items"), list)
    assert isinstance(data.get("total"), int)


def _create_task(client: TestClient) -> dict:
    payload_candidates = [
        {
            "title": f"pytest-task-{uuid4().hex[:8]}",
            "researcher_id": "r_alpha",
            "schedule_type": "cron",
            "schedule_config": {"expr": "0 9 * * 1-5"},
            "trade_day_only": False,
            "force_output_document": False,
            "description": "auto-generated by tests",
            "prompt_template": "test prompt {{date}}",
        },
        {
            "name": f"pytest-task-{uuid4().hex[:8]}",
            "task_type": "scheduled",
            "researcher_id": "r_alpha",
            "cron": "0 9 * * 1-5",
            "payload_prompt": "auto-generated by tests",
        },
    ]

    for payload in payload_candidates:
        response = client.post("/api/v1/tasks", json=payload)
        if response.status_code in (200, 201):
            return _assert_success_payload(response, expected_statuses=(200, 201))["data"]

    assert False, "Task create API payload did not match current contract."


def _extract_task_id(task_data: dict) -> str:
    task_id = task_data.get("task_id") or task_data.get("id")
    assert isinstance(task_id, str) and task_id
    return task_id


def _extract_run_id(run_data: dict) -> str:
    run_id = run_data.get("run_id") or run_data.get("id")
    assert isinstance(run_id, str) and run_id
    return run_id


def test_tasks_smoke_routes_and_list_contract() -> None:
    client = TestClient(create_app())

    tasks_data = _assert_success_payload(client.get("/api/v1/tasks"))["data"]
    _assert_list_response_container(tasks_data)

    task_id: str
    if tasks_data["items"]:
        task_id = _extract_task_id(tasks_data["items"][0])
    else:
        task_id = _extract_task_id(_create_task(client))

    runs_data = _assert_success_payload(client.get("/api/v1/tasks/runs"))["data"]
    _assert_list_response_container(runs_data)

    task_runs_data = _assert_success_payload(client.get(f"/api/v1/tasks/{task_id}/runs"))["data"]
    _assert_list_response_container(task_runs_data)

    _assert_success_payload(
        client.post(f"/api/v1/tasks/{task_id}/activate"),
        expected_statuses=(200, 202),
    )
    _assert_success_payload(
        client.post(f"/api/v1/tasks/{task_id}/pause"),
        expected_statuses=(200, 202),
    )


def test_tasks_create_patch_delete_flow() -> None:
    client = TestClient(create_app())

    created_task = _create_task(client)
    task_id = _extract_task_id(created_task)

    updated_title = f"pytest-task-updated-{uuid4().hex[:6]}"
    patch_data = _assert_success_payload(
        client.patch(
            f"/api/v1/tasks/{task_id}",
            json={"title": updated_title},
        ),
        expected_statuses=(200, 202),
    )["data"]
    if "title" in patch_data:
        assert patch_data["title"] == updated_title

    _assert_success_payload(
        client.delete(f"/api/v1/tasks/{task_id}"),
        expected_statuses=(200, 202),
    )

    effective_tasks = _assert_success_payload(client.get("/api/v1/tasks"))["data"]["items"]
    matched_items = [item for item in effective_tasks if _extract_task_id(item) == task_id]
    assert len(matched_items) <= 1
    if matched_items:
        status_value = str(matched_items[0].get("status", "")).upper()
        assert status_value == "DELETED"


def test_tasks_run_and_logs_contract() -> None:
    client = TestClient(create_app())

    task_id = _extract_task_id(_create_task(client))

    run_data = _assert_success_payload(
        client.post(f"/api/v1/tasks/{task_id}/run"),
        expected_statuses=(200, 201, 202),
    )["data"]
    run_id = _extract_run_id(run_data)

    task_runs_data = _assert_success_payload(client.get(f"/api/v1/tasks/{task_id}/runs"))["data"]
    _assert_list_response_container(task_runs_data)
    assert any(_extract_run_id(item) == run_id for item in task_runs_data["items"])

    all_runs_data = _assert_success_payload(client.get("/api/v1/tasks/runs"))["data"]
    _assert_list_response_container(all_runs_data)

    logs_data = _assert_success_payload(client.get(f"/api/v1/tasks/runs/{run_id}/logs"))["data"]
    _assert_list_response_container(logs_data)
